### ISSUE TITLE
My workplan

### ISSUE THREAD

**Issue by nivertech** [nivertech/mydoc_test#1]
Things to do:
- [ ] find thin client model
- [ ] buy server license
- [ ] send email to client
